### PR TITLE
Modified to work with HACS

### PR DESCRIPTION
**Pull request by mnestor**
Needed to move the component into a custom_components folder and create a manifest.json file in order to use this with HACS

Might also need to rename the repo? First time I got a custom component loaded and first time getting one working with HACS so I'm not sure.

### CODE REVIEW

**Comment by joshjcarrier** [comment]
Neat! I didn't know [HACS](https://custom-components.github.io/hacs/) existed. I'd like to see this component as part of Home Assistant, but this could work in the meantime. Will get HACS installed and test this out.

**Comment by mnestor** [comment]
I would like to see that to, it was rather painful when I did my last one but I'd be willing to help out if you need it.

**Comment by joshjcarrier** [comment]
Thanks for the PR! Let's roll with HACS for now since its so easy to support.

**Comment by thayneq** [comment]
how do I add this to HACS?

**Pull request merged**
